# Terraform Lint CI with tflint and GitHub Actions
# 認証はGitHub AppsのAppId/Secretを利用

name: Terraform Lint

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub App authentication
        id: app-auth
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: |
          tflint --init
          tflint --format=compact
        env:
          GITHUB_TOKEN: ${{ steps.app-auth.outputs.token }}
